import numpy as np
print ("####### random.read() #######")
A = np.random.rand (2,5)
print (A)
print ("####### random.randint() #######")
B = np.random.randint(2,17)
print(B)
print("####### random.randn() #######")
C = np.random.randn(2,5)
print(C)
print("####### random.random() #######")
D = np.random.random((2,5))
print(D)
print("####### random.multivariate_normal #######")
E = np.random.multivariate_normal([1.0,5.0], [[1.0,2.0],[2.0,1.0]],5)
print(E)
